name: CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./infra/docker/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/taskmgr:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/taskmgr:${{ steps.version.outputs.VERSION }}
          ${{ secrets.DOCKERHUB_USERNAME }}/taskmgr:${{ steps.version.outputs.TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
    
    - name: Notify Slack on Success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            text: "🚀 Deployment Successful!",
            attachments: [{
              color: 'good',
              text: `Version ${{ steps.version.outputs.TAG }} has been deployed to Docker Hub.\nImage: ${{ secrets.DOCKERHUB_USERNAME }}/taskmgr:${{ steps.version.outputs.VERSION }}`
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Notify Slack on Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            text: "❌ Deployment Failed!",
            attachments: [{
              color: 'danger',
              text: `Version ${{ steps.version.outputs.TAG }} failed to deploy. Check the logs.`
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        body: |
          ## 🐳 Docker Image
          
          ```bash
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/taskmgr:${{ steps.version.outputs.VERSION }}
          ```
          
          ## 📦 Quick Start
          
          ```bash
          docker run -d \
            -p 8000:8000 \
            -e DJANGO_SECRET_KEY=your-secret-key \
            ${{ secrets.DOCKERHUB_USERNAME }}/taskmgr:${{ steps.version.outputs.VERSION }}
          ```
          
          ## 📚 Documentation
          
          - API Docs: http://localhost:8000/api/v1/docs/
          - Health: http://localhost:8000/health
          
          ## What's Changed
          
          See the full changelog below.